### ISSUE TITLE
 "Actual test 16.5 iPhone es3 A15 CPU, the phone automatically restarts after pressing the kopen button"

### ISSUE THREAD

**Issue by ayun110** [felix-pb/kfd#11]
"Actual test 16.5 iPhone es3 A15 CPU, the phone automatically restarts after pressing the kopen button"

**Comment by felix-pb** [comment]
If you're having trouble finding this offset, then perhaps this project will help: https://github.com/tihmstar/libpatchfinder/tree/master/example/offsetexporter

Sorry I don't have time to provide help for finding offsets, so I'm going to close this issue. Good luck!
