### ISSUE TITLE
problem ios 16.0.3 iphone 11 pro

### ISSUE THREAD

**Issue by R3n3r0** [felix-pb/kfd#6]
I found the offsets with thimstar inserted into the project, the problem is that I get a kernel panic in info.h in the lines:
`u64 signed_pmap_kaddr = dynamic_kget(vm_map, pmap, kfd->info.kaddr.current_map);
    kfd->info.kaddr.current_pmap = unsign_kaddr(signed_pmap_kaddr);
    print_x64(kfd->info.kaddr.current_pmap);`

it's like the pmap offset is wrong, but I double-checked it by hand and everything looks correct.

**Comment by felix-pb** [comment]
Sorry I don't have time to provide that kind of support, so I'm going to close this issue. I hope your perseverance will pay off, good luck!
